from __future__ import annotations

from typing import List

from backend.models import UnifiedSignal


def build_demo_signals() -> List[UnifiedSignal]:
    return [
        UnifiedSignal(
            source="openweather",
            category="environmental",
            title="Rainfall deficit reaches severe level",
            text="Satellite-backed weather monitoring shows prolonged drought conditions in Northern Kenya.",
            region="Northern Kenya",
            country="Kenya",
            latitude=3.52,
            longitude=37.62,
            keywords=["drought", "rainfall deficit", "heatwave"],
            severity=0.93,
            metadata={"rainfall_anomaly": 0.88},
        ),
        UnifiedSignal(
            source="nasa_earthdata",
            category="environmental",
            title="Vegetation stress intensifies",
            text="Dryness indicators and low soil moisture suggest worsening pasture failure.",
            region="Northern Kenya",
            country="Kenya",
            latitude=3.52,
            longitude=37.62,
            keywords=["vegetation stress", "soil moisture deficit", "drought"],
            severity=0.89,
            metadata={"ndvi_delta": -0.34},
        ),
        UnifiedSignal(
            source="twitter",
            category="social",
            title="Residents report food shortages",
            text="Posts from Turkana mention empty grain shops, dead livestock, and long trips to find water.",
            region="Northern Kenya",
            country="Kenya",
            latitude=3.52,
            longitude=37.62,
            keywords=["food shortage", "dry wells", "livestock deaths"],
            severity=0.83,
            metadata={"engagement": 430},
        ),
        UnifiedSignal(
            source="telegram",
            category="social",
            title="Field update cites migration",
            text="Local coordinators say households are moving toward town centers after repeated borehole failures.",
            region="Northern Kenya",
            country="Kenya",
            latitude=3.52,
            longitude=37.62,
            keywords=["migration", "water scarcity", "borehole failure"],
            severity=0.77,
            metadata={"channel": "@ngo_field_updates"},
        ),
        UnifiedSignal(
            source="newsapi",
            category="news",
            title="Crop failure threatens regional food security",
            text="Newspaper coverage links delayed rains, failed harvests, and livestock deaths across northern counties.",
            region="Northern Kenya",
            country="Kenya",
            latitude=3.52,
            longitude=37.62,
            keywords=["crop failure", "food security", "drought"],
            severity=0.84,
            metadata={"publisher": "East Africa Daily"},
        ),
        UnifiedSignal(
            source="gdelt",
            category="news",
            title="Aid agencies warn of worsening hunger",
            text="Reports point to shrinking water access, rising displacement, and growing malnutrition pressure.",
            region="Northern Kenya",
            country="Kenya",
            latitude=3.52,
            longitude=37.62,
            keywords=["water scarcity", "malnutrition", "displacement"],
            severity=0.8,
            metadata={"tone": -5.7},
        ),
        UnifiedSignal(
            source="gfms",
            category="environmental",
            title="River flooding threatens low-lying communities",
            text="Flood monitoring shows elevated inundation risk across the Bangladesh Delta after intense rainfall.",
            region="Bangladesh Delta",
            country="Bangladesh",
            latitude=23.70,
            longitude=90.35,
            keywords=["flooding", "river overflow", "evacuation risk"],
            severity=0.74,
            metadata={"flood_depth_index": 0.81},
        ),
        UnifiedSignal(
            source="twitter",
            category="social",
            title="Residents post images of flooded homes",
            text="Social posts describe damaged shelters, blocked roads, and urgent needs for clean water in the delta.",
            region="Bangladesh Delta",
            country="Bangladesh",
            latitude=23.70,
            longitude=90.35,
            keywords=["flooding", "clean water", "road collapse"],
            severity=0.57,
            metadata={"engagement": 318},
        ),
        UnifiedSignal(
            source="newsapi",
            category="news",
            title="Floodwaters isolate villages in Bangladesh",
            text="Regional coverage links monsoon flooding to displacement, crop losses, and infrastructure breakdown.",
            region="Bangladesh Delta",
            country="Bangladesh",
            latitude=23.70,
            longitude=90.35,
            keywords=["displacement", "crop losses", "infrastructure breakdown"],
            severity=0.61,
            metadata={"publisher": "Dhaka Monitor"},
        ),
        UnifiedSignal(
            source="telegram",
            category="social",
            title="Aid coordinators flag cholera risk in Sudan",
            text="Field channels report population movement, water shortages, and disease pressure near overcrowded shelters.",
            region="Sudan",
            country="Sudan",
            latitude=15.50,
            longitude=32.56,
            keywords=["migration", "cholera", "water shortage"],
            severity=0.66,
            metadata={"channel": "@sudan_response"},
        ),
        UnifiedSignal(
            source="gdelt",
            category="news",
            title="Fighting and shortages intensify displacement in Sudan",
            text="News reports describe disrupted supply lines, medicine shortages, and major civilian displacement.",
            region="Sudan",
            country="Sudan",
            latitude=15.50,
            longitude=32.56,
            keywords=["displacement", "medicine shortage", "supply disruption"],
            severity=0.71,
            metadata={"tone": -7.1},
        ),
        UnifiedSignal(
            source="noaa_climate",
            category="environmental",
            title="Extreme heat compounds humanitarian stress",
            text="Climate anomaly indicators show extreme heat and poor water availability across affected areas in Sudan.",
            region="Sudan",
            country="Sudan",
            latitude=15.50,
            longitude=32.56,
            keywords=["extreme heat", "water scarcity", "climate anomaly"],
            severity=0.62,
            metadata={"temperature_anomaly": 0.63},
        ),
        UnifiedSignal(
            source="twitter",
            category="social",
            title="Communities in Haiti report blackout and clinic shortages",
            text="Posts cite power outages, fuel scarcity, and health facilities running low on medicines after storm damage.",
            region="Haiti",
            country="Haiti",
            latitude=18.59,
            longitude=-72.31,
            keywords=["power outage", "medicine shortage", "fuel scarcity"],
            severity=0.42,
            metadata={"engagement": 205},
        ),
        UnifiedSignal(
            source="mediastack",
            category="news",
            title="Storm damage strains hospitals and roads in Haiti",
            text="Media coverage points to damaged infrastructure, disrupted transport, and delayed aid access.",
            region="Haiti",
            country="Haiti",
            latitude=18.59,
            longitude=-72.31,
            keywords=["infrastructure breakdown", "road collapse", "aid access"],
            severity=0.5,
            metadata={"publisher": "Caribbean Desk"},
        ),
        UnifiedSignal(
            source="nasa_earthdata",
            category="environmental",
            title="Heavy rainfall footprint detected over Haiti",
            text="Satellite observations show saturated ground conditions and heightened landslide exposure.",
            region="Haiti",
            country="Haiti",
            latitude=18.59,
            longitude=-72.31,
            keywords=["heavy rainfall", "landslide risk", "saturated ground"],
            severity=0.44,
            metadata={"soil_saturation": 0.74},
        ),
    ]
